version: '3'

services:

  web:
    build:
      volumes:
      - ./index.php
      dockerfile: Dockerfile
    image: takehome-exam
    ports: 
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://guest:Z8zDntK3aC0l@54.251.133.139:27017/?authSource=logs_db